# Generated by Django 5.2.6 on 2026-03-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_remove_theme_palette_typography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='notification_email',
            field=models.EmailField(default='admin@adminrodeo.com', help_text='Email address for system notifications', max_length=254),
        ),
    ]
