# Generated by Django 5.2.6 on 2026-04-05 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_alter_siteconfig_notification_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='siteconfig',
            table='site_settings"."site_settings_siteconfig',
        ),
    ]
