# Generated by Django 5.2.6 on 2026-04-05 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multilanguage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pagetranslationstatus',
            table='multilanguage"."multilanguage_pagetranslationstatus',
        ),
    ]
