# Generated by Django 5.2.6 on 2026-02-26 04:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_create_commerce_schemas"),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pricing"."price_books',
                'indexes': [models.Index(fields=['store_id'], name='price_books_store_i_39eee9_idx'), models.Index(fields=['store_id', 'is_default'], name='price_books_store_i_d79e12_idx')],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField(blank=True, null=True)),
                ('variant_id', models.UUIDField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compare_at_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pricing.pricebook')),
            ],
            options={
                'db_table': 'pricing"."prices',
                'indexes': [models.Index(fields=['price_book'], name='prices_price_b_2dda5c_idx'), models.Index(fields=['product_id'], name='prices_product_c55324_idx'), models.Index(fields=['variant_id'], name='prices_variant_546ab9_idx')],
            },
        ),
    ]
