# Generated by Django 5.2.6 on 2026-03-28 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pilotfaa_faa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveIntegerField(help_text='Chapter number as printed in the handbook')),
                ('title', models.CharField(max_length=200)),
                ('source_page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('source_page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('parsed', 'Parsed'), ('drafted', 'Drafted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='drafted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapters', to='pilotfaa_faa.faasourcedocument')),
            ],
            options={
                'db_table': 'pilotfaa_chapter',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('fixed_wing_ppl', 'Private Pilot (Fixed-Wing)'), ('helicopter_ppl', 'Helicopter Private Pilot'), ('instrument_rating', 'Instrument Rating'), ('commercial_ppl', 'Commercial Pilot'), ('sport_pilot', 'Sport Pilot'), ('cfi', 'Certified Flight Instructor')], db_index=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('icon_emoji', models.CharField(blank=True, max_length=10)),
                ('banner_gradient', models.CharField(blank=True, max_length=200)),
                ('acs_code', models.CharField(blank=True, help_text='e.g. FAA-S-ACS-6C', max_length=40)),
                ('total_lessons', models.PositiveIntegerField(default=0, help_text='Denormalized — updated by signal')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('parsed', 'Parsed'), ('drafted', 'Drafted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='drafted', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acs_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acs_courses', to='pilotfaa_faa.faasourcedocument')),
                ('primary_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_courses', to='pilotfaa_faa.faasourcedocument')),
            ],
            options={
                'db_table': 'pilotfaa_course',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.CharField(help_text='Display number e.g. 5.2', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('video_text', 'Video + Text'), ('reference', 'Reference')], default='video_text', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_preview', models.BooleanField(db_index=True, default=False, help_text='True = visible to free-tier users')),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('parsed', 'Parsed'), ('drafted', 'Drafted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='drafted', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='pilotfaa_content.chapter')),
            ],
            options={
                'db_table': 'pilotfaa_lesson',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ACSTaskMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acs_area_code', models.CharField(db_index=True, help_text='e.g. I, II, IV', max_length=20)),
                ('acs_task_code', models.CharField(db_index=True, help_text='e.g. PA.I.B, PA.IV.A', max_length=20)),
                ('knowledge_type', models.CharField(choices=[('knowledge', 'Knowledge (K)'), ('risk', 'Risk Management (R)'), ('skill', 'Skill (S)')], default='knowledge', max_length=20)),
                ('knowledge_ref', models.CharField(blank=True, help_text='Specific item e.g. K1, R2', max_length=40)),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Primary lesson for this ACS task')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acs_mappings', to='pilotfaa_content.lesson')),
            ],
            options={
                'db_table': 'pilotfaa_acs_task_mapping',
            },
        ),
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField(blank=True, help_text='Verbatim FAA source — NEVER modify after import')),
                ('teaching_text', models.TextField(blank=True, help_text='Editor/AI-derived pedagogical text')),
                ('key_terms', models.JSONField(default=list, help_text='[{word, definition}, ...]')),
                ('callouts', models.JSONField(default=list, help_text='[{variant, label, body}, ...]')),
                ('source_page_ref', models.CharField(blank=True, help_text='e.g. p.5-2', max_length=40)),
                ('source_section_ref', models.CharField(blank=True, help_text='Section heading citation', max_length=100)),
                ('content_status', models.CharField(choices=[('imported', 'Imported'), ('parsed', 'Parsed'), ('drafted', 'Drafted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='drafted', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='pilotfaa_content.lesson')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_lesson_contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pilotfaa_lesson_content',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('parsed', 'Parsed'), ('drafted', 'Drafted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='drafted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='pilotfaa_content.course')),
            ],
            options={
                'db_table': 'pilotfaa_module',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='pilotfaa_content.module'),
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_version', models.PositiveIntegerField(default=1)),
                ('script_text', models.TextField(blank=True)),
                ('narration_text', models.TextField(blank=True)),
                ('ai_provider', models.CharField(blank=True, help_text='e.g. ElevenLabs, HeyGen, OpenAI-TTS', max_length=60)),
                ('ai_model', models.CharField(blank=True, max_length=80)),
                ('generation_status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('generated', 'Generated'), ('published', 'Published'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('video_url', models.URLField(blank=True)),
                ('caption_url', models.URLField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('source_refs', models.JSONField(default=list, help_text='[{document, chapter, page}, ...]')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Only one VideoAsset per lesson should be active')),
                ('generation_error', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_assets', to='pilotfaa_content.lesson')),
            ],
            options={
                'db_table': 'pilotfaa_video_asset',
                'ordering': ['-asset_version'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'sort_order'], name='pilotfaa_co_status_f36b00_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['chapter', 'sort_order'], name='pilotfaa_le_chapter_ce7600_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['status', 'is_preview'], name='pilotfaa_le_status_b0bc81_idx'),
        ),
        migrations.AddIndex(
            model_name='acstaskmapping',
            index=models.Index(fields=['acs_task_code'], name='pilotfaa_ac_acs_tas_99d91e_idx'),
        ),
        migrations.AddIndex(
            model_name='acstaskmapping',
            index=models.Index(fields=['acs_area_code'], name='pilotfaa_ac_acs_are_8e6af5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='acstaskmapping',
            unique_together={('lesson', 'acs_task_code', 'knowledge_ref')},
        ),
        migrations.AddIndex(
            model_name='lessoncontent',
            index=models.Index(fields=['content_status'], name='pilotfaa_le_content_e8f5fc_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'sort_order'], name='pilotfaa_mo_course__1f9182_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['module', 'sort_order'], name='pilotfaa_ch_module__0bab9b_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['source_document', 'chapter_number'], name='pilotfaa_ch_source__169d21_idx'),
        ),
        migrations.AddIndex(
            model_name='videoasset',
            index=models.Index(fields=['lesson', 'is_active'], name='pilotfaa_vi_lesson__a3ec33_idx'),
        ),
        migrations.AddIndex(
            model_name='videoasset',
            index=models.Index(fields=['generation_status'], name='pilotfaa_vi_generat_a7b10b_idx'),
        ),
    ]
