# Generated by Django 5.2.6 on 2025-12-12 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for this connection', max_length=255)),
                ('engine', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlite', 'SQLite')], help_text='Database engine type', max_length=50)),
                ('host', models.CharField(help_text='Database host', max_length=255)),
                ('port', models.IntegerField(help_text='Database port')),
                ('username', models.CharField(help_text='Database username', max_length=255)),
                ('password', models.TextField(help_text='Encrypted database password')),
                ('database_name', models.CharField(help_text='Database name', max_length=255)),
                ('schema', models.CharField(blank=True, help_text='Default schema (optional)', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this connection active?')),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default connection?')),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='disconnected', help_text='Connection status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_checked', models.DateTimeField(blank=True, help_text='Last connection test time', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='database_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Database Connection',
                'verbose_name_plural': 'Database Connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('connect', 'Connect'), ('disconnect', 'Disconnect'), ('query', 'Query'), ('preview', 'Preview'), ('list_schemas', 'List Schemas'), ('list_tables', 'List Tables'), ('list_columns', 'List Columns'), ('test_connection', 'Test Connection')], help_text='Action performed', max_length=50)),
                ('query', models.TextField(blank=True, help_text='SQL query executed (if applicable)', null=True)),
                ('table_name', models.CharField(blank=True, help_text='Table name (if applicable)', max_length=255, null=True)),
                ('schema_name', models.CharField(blank=True, help_text='Schema name (if applicable)', max_length=255, null=True)),
                ('execution_time', models.FloatField(blank=True, help_text='Query execution time in seconds', null=True)),
                ('success', models.BooleanField(help_text='Was the operation successful?')),
                ('error_message', models.TextField(blank=True, help_text='Error message if operation failed', null=True)),
                ('rows_returned', models.IntegerField(blank=True, help_text='Number of rows returned', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='database_activities', to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(help_text='Database connection used', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='db_management.databaseconnection')),
            ],
            options={
                'verbose_name': 'Database Activity Log',
                'verbose_name_plural': 'Database Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='databaseconnection',
            index=models.Index(fields=['engine', 'is_active'], name='db_manageme_engine_417317_idx'),
        ),
        migrations.AddIndex(
            model_name='databaseconnection',
            index=models.Index(fields=['status', '-last_checked'], name='db_manageme_status_924d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='databaseactivitylog',
            index=models.Index(fields=['connection', '-created_at'], name='db_manageme_connect_2f1193_idx'),
        ),
        migrations.AddIndex(
            model_name='databaseactivitylog',
            index=models.Index(fields=['user', '-created_at'], name='db_manageme_user_id_adf6f7_idx'),
        ),
        migrations.AddIndex(
            model_name='databaseactivitylog',
            index=models.Index(fields=['action', '-created_at'], name='db_manageme_action_dea985_idx'),
        ),
        migrations.AddIndex(
            model_name='databaseactivitylog',
            index=models.Index(fields=['success', '-created_at'], name='db_manageme_success_dca141_idx'),
        ),
    ]
