# Generated by Django 5.2.6 on 2025-12-13 01:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabasePerformanceMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ping_time', models.FloatField(blank=True, help_text='Connection latency in milliseconds', null=True)),
                ('query_time', models.FloatField(blank=True, help_text='Query execution time in milliseconds', null=True)),
                ('total_collection_time', models.FloatField(blank=True, help_text='Total time to collect all metrics in milliseconds', null=True)),
                ('database_size', models.BigIntegerField(blank=True, help_text='Database size in bytes', null=True)),
                ('table_count', models.IntegerField(blank=True, help_text='Number of tables', null=True)),
                ('index_count', models.IntegerField(blank=True, help_text='Number of indexes', null=True)),
                ('connection_count', models.IntegerField(blank=True, help_text='Active connections', null=True)),
                ('cache_hit_ratio', models.FloatField(blank=True, help_text='Cache hit ratio percentage (PostgreSQL)', null=True)),
                ('uptime', models.CharField(blank=True, help_text='Database uptime', max_length=255, null=True)),
                ('version', models.TextField(blank=True, help_text='Database version string', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('connection', models.ForeignKey(help_text='Database connection these metrics belong to', on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='db_management.databaseconnection')),
            ],
            options={
                'verbose_name': 'Database Performance Metric',
                'verbose_name_plural': 'Database Performance Metrics',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'indexes': [models.Index(fields=['connection', '-created_at'], name='db_manageme_connect_045682_idx'), models.Index(fields=['-created_at'], name='db_manageme_created_ffc9c7_idx')],
            },
        ),
    ]
