# Generated by Django 5.2.6 on 2026-04-05 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_management', '0002_databaseperformancemetrics'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='databaseactivitylog',
            table='db_management"."db_management_databaseactivitylog',
        ),
        migrations.AlterModelTable(
            name='databaseconnection',
            table='db_management"."db_management_databaseconnection',
        ),
        migrations.AlterModelTable(
            name='databaseperformancemetrics',
            table='db_management"."db_management_databaseperformancemetrics',
        ),
    ]
