# Generated by Django 5.2.6 on 2026-04-05 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='billingaddress',
            table='financials"."financials_billingaddress',
        ),
        migrations.AlterModelTable(
            name='billingtransaction',
            table='financials"."financials_billingtransaction',
        ),
        migrations.AlterModelTable(
            name='coinbasecharge',
            table='financials"."financials_coinbasecharge',
        ),
        migrations.AlterModelTable(
            name='coinbasetransaction',
            table='financials"."financials_coinbasetransaction',
        ),
        migrations.AlterModelTable(
            name='paymentmethod',
            table='financials"."financials_paymentmethod',
        ),
        migrations.AlterModelTable(
            name='paymentproviderconfig',
            table='financials"."financials_paymentproviderconfig',
        ),
        migrations.AlterModelTable(
            name='promotionaldeal',
            table='financials"."financials_promotionaldeal',
        ),
        migrations.AlterModelTable(
            name='subscriptionplan',
            table='financials"."financials_subscriptionplan',
        ),
        migrations.AlterModelTable(
            name='usersubscription',
            table='financials"."financials_usersubscription',
        ),
    ]
