# Generated by Django 5.2.6 on 2026-04-05 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_emailcapture_form_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailcapture',
            table='emails"."emails_emailcapture',
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='emails"."emails_feedback',
        ),
        migrations.AlterModelTable(
            name='updatesignup',
            table='emails"."emails_updatesignup',
        ),
    ]
