# Generated by Django 5.2.6 on 2026-03-28 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pilotfaa_content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('progress_pct', models.PositiveIntegerField(default=0, help_text='0-100, denormalized — updated by signal')),
                ('total_time_seconds', models.BigIntegerField(default=0, help_text='Accumulated study time — updated by signal')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='enrollments', to='pilotfaa_content.course')),
                ('last_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pilotfaa_content.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilotfaa_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pilotfaa_enrollment',
            },
        ),
        migrations.CreateModel(
            name='LessonCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_pct', models.PositiveIntegerField(default=0)),
                ('read_pct', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('first_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_completions', to='pilotfaa_progress.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='pilotfaa_content.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilotfaa_lesson_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pilotfaa_lesson_completion',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Note', max_length=300)),
                ('source_ref', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete — filter WHERE deleted_at IS NULL', null=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='pilotfaa_content.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilotfaa_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pilotfaa_note',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='NULL until session closes', null=True)),
                ('activity_type', models.CharField(choices=[('lesson', 'Lesson'), ('quiz', 'Quiz'), ('tutor', 'AI Tutor'), ('reference', 'Reference')], db_index=True, default='lesson', max_length=20)),
                ('device_type', models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('tablet', 'Tablet'), ('mobile', 'Mobile')], max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='pilotfaa_progress.enrollment')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_sessions', to='pilotfaa_content.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilotfaa_study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pilotfaa_study_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('source_ref', models.CharField(blank=True, max_length=200)),
                ('excerpt', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('lesson', 'Lesson'), ('phak', 'PHAK'), ('faraim', 'FAR/AIM'), ('acs', 'ACS'), ('quiz', 'Quiz')], db_index=True, default='lesson', max_length=20)),
                ('tag_label', models.CharField(blank=True, max_length=60)),
                ('tag_variant', models.CharField(blank=True, help_text='blue | gold | green | red | amber', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookmarks', to='pilotfaa_content.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilotfaa_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pilotfaa_bookmark',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'category'], name='pilotfaa_bo_user_id_f0f9e8_idx'), models.Index(fields=['user', '-created_at'], name='pilotfaa_bo_user_id_3c1507_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'status'], name='pilotfaa_en_user_id_e7b266_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'status'], name='pilotfaa_en_course__a5a0b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='lessoncompletion',
            index=models.Index(fields=['enrollment', 'completed'], name='pilotfaa_le_enrollm_bfecc9_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoncompletion',
            index=models.Index(fields=['user', 'completed'], name='pilotfaa_le_user_id_a6edee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessoncompletion',
            unique_together={('user', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', '-updated_at'], name='pilotfaa_no_user_id_8929d1_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'deleted_at'], name='pilotfaa_no_user_id_330c6c_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'started_at'], name='pilotfaa_st_user_id_6d7afe_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['enrollment', 'started_at'], name='pilotfaa_st_enrollm_e6dcc0_idx'),
        ),
    ]
