# Generated by Django 5.2.6 on 2026-03-28 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pilotfaa_content', '0001_initial'),
        ('pilotfaa_progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bank_type', models.CharField(choices=[('chapter', 'Chapter Quiz'), ('mock_exam', 'Mock Exam'), ('remediation', 'Remediation'), ('custom', 'Custom')], db_index=True, default='chapter', max_length=20)),
                ('question_count', models.PositiveIntegerField(default=0, help_text='Denormalized — updated by signal')),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, help_text='NULL = untimed', null=True)),
                ('pass_threshold_pct', models.PositiveIntegerField(default=70)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_banks', to='pilotfaa_content.chapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='pilotfaa_content.course')),
            ],
            options={
                'db_table': 'pilotfaa_question_bank',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('true_false', 'True / False'), ('matching', 'Matching'), ('scenario', 'Scenario'), ('oral_prep', 'Oral Prep')], db_index=True, default='single_choice', max_length=20)),
                ('options', models.JSONField(default=list, help_text='[{letter, text, is_correct}, ...]')),
                ('correct_letter', models.CharField(blank=True, help_text='Single-choice correct answer. Blank for other types.', max_length=4)),
                ('rationale', models.TextField()),
                ('rationale_source_ref', models.CharField(help_text='Full citation e.g. PHAK FAA-H-8083-25C · Ch.5 p.5-12', max_length=200)),
                ('phak_page', models.CharField(blank=True, max_length=20)),
                ('acs_task_code', models.CharField(blank=True, db_index=True, help_text='Primary ACS task e.g. PA.I.B.K1', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='medium', max_length=10)),
                ('exam_relevant', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('active', 'Active'), ('retired', 'Retired')], db_index=True, default='draft', max_length=10)),
                ('times_answered', models.BigIntegerField(default=0, help_text='Denormalized — updated by signal')),
                ('times_correct', models.BigIntegerField(default=0, help_text='Denormalized — updated by signal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='pilotfaa_content.chapter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pilotfaa_assessments.questionbank')),
            ],
            options={
                'db_table': 'pilotfaa_question',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_type', models.CharField(choices=[('chapter_quiz', 'Chapter Quiz'), ('mock_exam', 'Mock Exam'), ('remediation', 'Remediation'), ('custom', 'Custom')], db_index=True, default='chapter_quiz', max_length=20)),
                ('score_pct', models.PositiveIntegerField(blank=True, help_text='NULL until completed', null=True)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, db_index=True, help_text='NULL until completed', null=True)),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='attempts', to='pilotfaa_assessments.questionbank')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='pilotfaa_progress.enrollment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilotfaa_quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pilotfaa_quiz_attempt',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_letter', models.CharField(blank=True, help_text='NULL/blank if skipped', max_length=4)),
                ('selected_letters', models.JSONField(blank=True, help_text='Array for multiple_choice', null=True)),
                ('is_correct', models.BooleanField(db_index=True, default=False)),
                ('time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='responses', to='pilotfaa_assessments.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='pilotfaa_assessments.quizattempt')),
            ],
            options={
                'db_table': 'pilotfaa_question_response',
            },
        ),
        migrations.CreateModel(
            name='TopicMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acs_task_code', models.CharField(blank=True, db_index=True, help_text='Blank = chapter-level rollup row', max_length=20)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('mastery_pct', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=5)),
                ('is_weak', models.BooleanField(db_index=True, default=False)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_mastery', to='pilotfaa_content.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilotfaa_topic_mastery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pilotfaa_topic_mastery',
            },
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['course', 'bank_type', 'is_active'], name='pilotfaa_qu_course__9bab37_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['bank', 'status'], name='pilotfaa_qu_bank_id_7d3b8b_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['chapter', 'difficulty'], name='pilotfaa_qu_chapter_200946_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', '-completed_at'], name='pilotfaa_qu_user_id_04a0fb_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['enrollment', 'attempt_type'], name='pilotfaa_qu_enrollm_9a6265_idx'),
        ),
        migrations.AddIndex(
            model_name='questionresponse',
            index=models.Index(fields=['attempt'], name='pilotfaa_qu_attempt_0b3a66_idx'),
        ),
        migrations.AddIndex(
            model_name='questionresponse',
            index=models.Index(fields=['question', 'is_correct'], name='pilotfaa_qu_questio_26456f_idx'),
        ),
        migrations.AddIndex(
            model_name='topicmastery',
            index=models.Index(fields=['user', 'is_weak'], name='pilotfaa_to_user_id_54f6b7_idx'),
        ),
        migrations.AddIndex(
            model_name='topicmastery',
            index=models.Index(fields=['user', 'mastery_pct'], name='pilotfaa_to_user_id_1637ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topicmastery',
            unique_together={('user', 'chapter', 'acs_task_code')},
        ),
    ]
