# Generated by Django 5.2.6 on 2026-04-05 21:54
#
# PostgreSQL: move tables with ALTER TABLE ... SET SCHEMA.
# AlterModelTable alone emits RENAME TO "blog"."..." which is invalid SQL.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE SCHEMA IF NOT EXISTS blog;
                    ALTER TABLE public.blog_category SET SCHEMA blog;
                    ALTER TABLE public.blog_tag SET SCHEMA blog;
                    ALTER TABLE public.blog_blogauthor SET SCHEMA blog;
                    ALTER TABLE public.blog_blogpost SET SCHEMA blog;
                    ALTER TABLE public.blog_blogpost_tags SET SCHEMA blog;
                    """,
                    reverse_sql="""
                    ALTER TABLE blog.blog_blogpost_tags SET SCHEMA public;
                    ALTER TABLE blog.blog_blogpost SET SCHEMA public;
                    ALTER TABLE blog.blog_blogauthor SET SCHEMA public;
                    ALTER TABLE blog.blog_tag SET SCHEMA public;
                    ALTER TABLE blog.blog_category SET SCHEMA public;
                    DROP SCHEMA IF EXISTS blog;
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterModelTable(name='category', table='blog.blog_category'),
                migrations.AlterModelTable(name='tag', table='blog.blog_tag'),
                migrations.AlterModelTable(name='blogauthor', table='blog.blog_blogauthor'),
                migrations.AlterModelTable(name='blogpost', table='blog.blog_blogpost'),
            ],
        ),
    ]
