# Generated by Django 5.2.6 on 2026-04-05 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blogauthor',
            table='blog"."blog_blogauthor',
        ),
        migrations.AlterModelTable(
            name='blogpost',
            table='blog"."blog_blogpost',
        ),
        migrations.AlterModelTable(
            name='category',
            table='blog"."blog_category',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='blog"."blog_tag',
        ),
    ]
