# Generated by Django 5.2.6 on 2026-02-26 04:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_create_commerce_schemas"),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('location_type', models.CharField(choices=[('warehouse', 'Warehouse'), ('store', 'Store'), ('virtual', 'Virtual')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory"."inventory_locations',
            },
        ),
        migrations.CreateModel(
            name='InventoryLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant_id', models.UUIDField()),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('quantity_reserved', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorylocation')),
            ],
            options={
                'db_table': 'inventory"."inventory_levels',
                'indexes': [models.Index(fields=['variant_id'], name='inventory_l_variant_db0b6d_idx'), models.Index(fields=['location'], name='inventory_l_locatio_f2af6c_idx')],
                'unique_together': {('variant_id', 'location')},
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant_id', models.UUIDField()),
                ('movement_type', models.CharField(choices=[('sale', 'Sale'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('restock', 'Restock'), ('reservation', 'Reservation')], max_length=50)),
                ('quantity_delta', models.IntegerField()),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorylocation')),
            ],
            options={
                'db_table': 'inventory"."inventory_movements',
                'indexes': [models.Index(fields=['variant_id'], name='inventory_m_variant_7844dc_idx'), models.Index(fields=['movement_type'], name='inventory_m_movemen_a3c722_idx')],
            },
        ),
    ]
