# Generated by Django 5.2.6 on 2026-03-28 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAASourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(help_text='e.g. PHAK, RFH, IFH, ACS_PPL', max_length=40)),
                ('full_title', models.TextField(help_text='Full official title')),
                ('publication_ref', models.CharField(help_text='e.g. FAA-H-8083-25C', max_length=80)),
                ('version', models.CharField(help_text='e.g. 2023-09, Rev C', max_length=40)),
                ('effective_date', models.DateField()),
                ('source_url', models.URLField(blank=True, help_text='Canonical FAA.gov or eCFR.gov URL')),
                ('pdf_s3_key', models.TextField(blank=True, help_text='S3 key for cached PDF copy')),
                ('chapter_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True, help_text='False once superseded by a newer version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='pilotfaa_faa.faasourcedocument')),
            ],
            options={
                'db_table': 'pilotfaa_faa_source_document',
                'ordering': ['short_code', '-effective_date'],
                'indexes': [models.Index(fields=['is_current', 'short_code'], name='pilotfaa_fa_is_curr_50b6ea_idx')],
                'unique_together': {('short_code', 'version')},
            },
        ),
    ]
