# Generated by Django 5.2.6 on 2026-04-05 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multilocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='location',
            table='multilocation"."multilocation_location',
        ),
        migrations.AlterModelTable(
            name='runnerhealth',
            table='multilocation"."multilocation_runnerhealth',
        ),
    ]
