# Generated by Django 5.2.6 on 2026-03-28 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pilotfaa_content', '0001_initial'),
        ('pilotfaa_faa', '0001_initial'),
        ('pilotfaa_progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_mode', models.CharField(choices=[('learn', 'Learn'), ('review', 'Review'), ('cram', 'Cram'), ('oral_prep', 'Oral Prep'), ('mock_exam', 'Mock Exam')], db_index=True, default='learn', max_length=20)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tutor_sessions', to='pilotfaa_content.course')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_sessions', to='pilotfaa_progress.enrollment')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_sessions', to='pilotfaa_content.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilotfaa_tutor_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pilotfaa_tutor_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant')], db_index=True, max_length=20)),
                ('content', models.TextField()),
                ('intent_type', models.CharField(blank=True, choices=[('concept_explanation', 'Concept Explanation'), ('regulation', 'Regulation'), ('exam_prep', 'Exam Prep'), ('oral_prep', 'Oral Prep'), ('comparison', 'Comparison'), ('summary', 'Summary'), ('quiz_request', 'Quiz Request'), ('navigation', 'Navigation'), ('other', 'Other')], db_index=True, max_length=30)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=3, help_text='0.000–1.000. NULL for user messages.', max_digits=4, null=True)),
                ('grounded', models.BooleanField(blank=True, db_index=True, help_text='True = grounded in approved FAA sources. NULL for user msgs.', null=True)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('ai_model', models.CharField(blank=True, help_text='e.g. claude-opus-4-5', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pilotfaa_tutor.tutorsession')),
            ],
            options={
                'db_table': 'pilotfaa_tutor_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful'), ('incorrect', 'Incorrect'), ('missing_citation', 'Missing Citation')], db_index=True, max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilotfaa_message_feedback', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='pilotfaa_tutor.tutormessage')),
            ],
            options={
                'db_table': 'pilotfaa_message_feedback',
                'indexes': [models.Index(fields=['rating'], name='pilotfaa_me_rating_2a7ee1_idx')],
                'unique_together': {('message', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MessageCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_doc_ref', models.CharField(help_text='Short ref e.g. PHAK FAA-H-8083-25C', max_length=100)),
                ('chapter_ref', models.CharField(blank=True, help_text='e.g. Ch.5, Part 61', max_length=40)),
                ('section_ref', models.CharField(blank=True, max_length=100)),
                ('page_ref', models.CharField(blank=True, help_text='e.g. p.5-12, §91.155', max_length=20)),
                ('extracted_span', models.TextField(blank=True, help_text='Exact FAA text passage that grounded this citation')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citations', to='pilotfaa_faa.faasourcedocument')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='pilotfaa_tutor.tutormessage')),
            ],
            options={
                'db_table': 'pilotfaa_message_citation',
                'ordering': ['sort_order'],
                'indexes': [models.Index(fields=['message', 'sort_order'], name='pilotfaa_me_message_132107_idx'), models.Index(fields=['source_document'], name='pilotfaa_me_source__f9ddab_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tutorsession',
            index=models.Index(fields=['user', '-started_at'], name='pilotfaa_tu_user_id_4a3187_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorsession',
            index=models.Index(fields=['enrollment'], name='pilotfaa_tu_enrollm_85915c_idx'),
        ),
        migrations.AddIndex(
            model_name='tutormessage',
            index=models.Index(fields=['session', 'created_at'], name='pilotfaa_tu_session_51b0ed_idx'),
        ),
        migrations.AddIndex(
            model_name='tutormessage',
            index=models.Index(fields=['intent_type'], name='pilotfaa_tu_intent__d64972_idx'),
        ),
    ]
