# Generated by Django 5.2.6 on 2025-12-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_billingaddress_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='requested_demo',
            field=models.BooleanField(default=False, help_text='Whether the user has requested a demo'),
        ),
    ]
