# Generated by Django 5.2.6 on 2026-04-05 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_userprofile_role_student'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='monitoredsite',
            table='users"."users_monitoredsite',
        ),
        migrations.AlterModelTable(
            name='useractivity',
            table='users"."users_useractivity',
        ),
        migrations.AlterModelTable(
            name='usercorporateprofile',
            table='users"."users_usercorporateprofile',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='users"."users_userprofile',
        ),
    ]
